### ISSUE TITLE
Question: Regarding unauth-guard

### ISSUE THREAD

**Issue by andlcool** [r-park/todo-angular2-firebase#109]
I have 2 questions for my learning. In your unauth-guard.ts
1. Why `!authState` return primitive boolean but when `console.log(!authState)` shows as object
2. Why console.log(unauthenticated); gets printed but console.log('there', x) cannot be printed.

Thanks.

```
 canActivate(route: ActivatedRouteSnapshot): Observable<boolean> {
    let y = this.getAuthState();
    console.log('buddy' ,y);

    return this.af.auth
      .take(1)
      .map(authState => !authState)
      .do(unauthenticated => {
        console.log(unauthenticated);
        /*if (!unauthenticated) {
          this.router.navigate(['/dashboard']);
        } */
      });
  }

  getAuthState() : Observable<any> {
    return this.af.auth
      .take(1)
      .map(authState => !authState)
      .do(x => {console.log('there', x)});
  }
```

**Comment by r-park** [comment]
`console.log('there', x)` will not print until you subscribe to the observable that is being returned by `getAuthState()`:

```js
let y = this.getAuthState();
y.subscribe(value => console.log('buddy', y));
```
Angular2 subscribes to the observable returned by `canActivate()` and uses the emitted value to determine if the route should be activated.
