### ISSUE TITLE
firebase login

### ISSUE THREAD

**Issue by foxjazz** [r-park/todo-angular2-firebase#117]
what the heck does this mean?
Error: Cannot run login in non-interactive mode. See login:ci to generate a token for use in non-interactive environments.

**Comment by LukeSchlangen** [comment]
Seems like this is a firebase issue and not necessarily related to this repo?
https://github.com/firebase/firebase-tools/issues/77

**Comment by hammy-109** [comment]
firebase login:ci --interactive

 this is the solution
