### ISSUE TITLE
How to deploy the app after successful build? No 'target' folder.

### ISSUE THREAD

**Issue by tanvirshuvo** [r-park/todo-angular2-firebase#122]
I have installed the app with npm install, used it as a boilerplate, and developed an application.

Now, when I tried to deploy the app to firebase, I noticed I don't have any target folder in my project directory. Then, how will I be able to deploy the app? What can be done to achieve a target folder with all the html, css and js files?

**Comment by r-park** [comment]
Hi @tanvirshuvo — did you remember to run the build command?
```shell
npm run build
```

**Comment by tanvirshuvo** [comment]
npm run build works. I get a target folder with index.html and some js, css. But when I deploy the folder to firebase the hosted app shows nothing. Just the app title ( <title>..</title>) shows in the tab head of the browser. But the app is working fine in the development machine. Is that something with angular's production/development environment option?
