### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by hbela** [r-park/todo-angular2-firebase#123]
Hi, tried to build the todo, but it failed, can you help ? thanks.

> todo-angular2-firebase@0.8.0 postbuild C:\MYAPP\ANGULAR2\todo-angular2-firebas
e-master
> ./bin/postbuild.copy-assets.sh

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! todo-angular2-firebase@0.8.0 postbuild: `./bin/postbuild.copy-assets.sh
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the todo-angular2-firebase@0.8.0 postbuild script './bin/post
build.copy-assets.sh'.

**Comment by r-park** [comment]
Hi @hbela — I've replaced the shell script with a webpack plugin for copying assets. The changes have been merged into the master branch.
