### ISSUE TITLE
TypeScript "Cannot find name" errors

### ISSUE THREAD

**Issue by joshdobbs** [r-park/todo-angular2-firebase#131]
I have cloned the repo, ran "npm install" and then "npm start" which results in the following errors. I have searched and searched but cannot figure out how to to resolve these issues.

`                  index.html     1.8 kB          [emitted]
chunk    {0} vendor.js, vendor.js.map (vendor) 1.98 MB {2} [initial] [rendered]
chunk    {1} main.js, main.js.map (main) 409 kB {0} [initial] [rendered]
chunk    {2} polyfills.js, polyfills.js.map (polyfills) 396 kB [entry] [rendered
]

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(47,36): error TS2304: Cannot find name 'Iterable'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(350,48): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(351,52): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(352,34): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(353,34): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(354,34): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(355,61): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(356,60): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(357,65): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(357,97): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(358,60): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(359,58): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(360,59): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(361,58): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(362,61): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(362,117): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(363,42): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(365,81): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(366,78): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(367,76): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(368,73): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(431,6): error TS2304: Cannot find name 'Symbol'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(464,59): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(465,59): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(467,48): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(468,69): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(472,40): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(474,48): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(494,55): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(495,45): error TS2304: Cannot find name 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(511,46): error TS2304: Cannot find name 'Iterable'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(512,43): error TS2304: Cannot find name 'Iterable'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(627,18): error TS2304: Cannot find name 'PromiseConstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(642,32): error TS2304: Cannot find name 'Iterable'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(646,39): error TS2304: Cannot find name 'Iterable'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(646,53): error TS2304: Cannot find name 'Iterator'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1280,34): error TS2339: Property 'for' does not exist on type 'SymbolConstructo
r'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1284,41): error TS2339: Property 'hasInstance' does not exist on type 'SymbolCo
nstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1288,48): error TS2339: Property 'isConcatSpreadable' does not exist on type 'S
ymbolConstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1292,38): error TS2339: Property 'iterator' does not exist on type 'SymbolConst
ructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1296,36): error TS2339: Property 'keyFor' does not exist on type 'SymbolConstru
ctor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1300,35): error TS2339: Property 'match' does not exist on type 'SymbolConstruc
tor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1304,37): error TS2339: Property 'replace' does not exist on type 'SymbolConstr
uctor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1308,36): error TS2339: Property 'search' does not exist on type 'SymbolConstru
ctor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1312,37): error TS2339: Property 'species' does not exist on type 'SymbolConstr
uctor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1316,35): error TS2339: Property 'split' does not exist on type 'SymbolConstruc
tor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1320,41): error TS2339: Property 'toPrimitive' does not exist on type 'SymbolCo
nstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1324,41): error TS2339: Property 'toStringTag' does not exist on type 'SymbolCo
nstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(1328,41): error TS2339: Property 'unscopables' does not exist on type 'SymbolCo
nstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2059,34): error TS2339: Property 'for' does not exist on type 'SymbolConstructo
r'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2063,41): error TS2339: Property 'hasInstance' does not exist on type 'SymbolCo
nstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2067,48): error TS2339: Property 'isConcatSpreadable' does not exist on type 'S
ymbolConstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2071,38): error TS2339: Property 'iterator' does not exist on type 'SymbolConst
ructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2075,36): error TS2339: Property 'keyFor' does not exist on type 'SymbolConstru
ctor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2079,35): error TS2339: Property 'match' does not exist on type 'SymbolConstruc
tor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2083,37): error TS2339: Property 'replace' does not exist on type 'SymbolConstr
uctor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2087,36): error TS2339: Property 'search' does not exist on type 'SymbolConstru
ctor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2091,37): error TS2339: Property 'species' does not exist on type 'SymbolConstr
uctor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2095,35): error TS2339: Property 'split' does not exist on type 'SymbolConstruc
tor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2099,41): error TS2339: Property 'toPrimitive' does not exist on type 'SymbolCo
nstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2103,41): error TS2339: Property 'toStringTag' does not exist on type 'SymbolCo
nstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@types\core
-js\index.d.ts
(2107,41): error TS2339: Property 'unscopables' does not exist on type 'SymbolCo
nstructor'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\rxjs\Observ
able.d.ts
(66,60): error TS2693: 'Promise' only refers to a type, but is being used as a v
alue here.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@angular\co
re\src\facade\lang.d.ts
(12,17): error TS2693: 'Map' only refers to a type, but is being used as a value
 here.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\@angular\co
re\src\facade\lang.d.ts
(13,17): error TS2693: 'Set' only refers to a type, but is being used as a value
 here.
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  4.39 kB       0
    chunk    {0} index.html 1.8 kB [entry] [rendered]
webpack: Failed to compile.
`

**Comment by r-park** [comment]
@joshdobbs thanks for the heads-up 👍 
Should be fixed now.

**Comment by joshdobbs** [comment]
@r-park I pulled and tried running "npm start" and get the following errors.


` 65% building modules 598/642 modules 44 active ...latform-browser\src\facade\br
 65% building modules 599/642 modules 43 active ...latform-browser\src\facade\br
 66% building modules 600/642 modules 42 active ...latform-browser\src\facade\br
 66% building modules 601/642 modules 41 active ...latform-browser\src\facade\br
 66% building modules 602/642 modules 40 active ...latform-browser\src\facade\br
 66% building modules 603/642 modules 39 active ...latform-browser\src\facade\br
 66% building modules 604/642 modules 38 active ...latform-browser\src\facade\br
 66% building modules 605/642 modules 37 active ...latform-browser\src\facade\br
 66% building modules 606/642 modules 36 active ...latform-browser\src\facade\br
 66% building modules 607/642 modules 35 active ...latform-browser\src\facade\br
 66% building modules 608/642 modules 34 active ...latform-browser\src\facade\br
 66% building modules 609/642 modules 33 active ...latform-browser\src\facade\br
 67% building modules 610/642 modules 32 active ...latform-browser\src\facade\br
 67% building modules 611/642 modules 31 active ...latform-browser\src\facade\br
 67% building modules 612/642 modules 30 active ...latform-browser\src\facade\br
 67% building modules 613/642 modules 29 active ...latform-browser\src\facade\br
 67% building modules 614/642 modules 28 active ...latform-browser\src\facade\br
 67% building modules 615/642 modules 27 active ...latform-browser\src\facade\br
 67% building modules 616/642 modules 26 active ...latform-browser\src\facade\br
 67% building modules 617/642 modules 25 active ...latform-browser\src\facade\br
 67% building modules 618/642 modules 24 active ...latform-browser\src\facade\br
 67% building modules 619/642 modules 23 active ...latform-browser\src\facade\br
 67% building modules 620/642 modules 22 active ...latform-browser\src\facade\br
 68% building modules 621/642 modules 21 active ...latform-browser\src\facade\br
 67% building modules 621/643 modules 22 active ..._modules\firebase\firebase-br
 67% building modules 621/644 modules 23 active ...ode_modules\angularfire2\auth
 67% building modules 621/645 modules 24 active ...les\angularfire2\auth\auth_ba
 67% building modules 621/646 modules 25 active ...re2\auth\firebase_sdk_auth_ba
 67% building modules 621/647 modules 26 active ...les\angularfire2\database\dat
 67% building modules 621/648 modules 27 active ...re2\database\firebase_list_fa
 67% building modules 621/649 modules 28 active ...\database\firebase_list_obser
 67% building modules 621/650 modules 29 active ...2\database\firebase_object_fa
 67% building modules 621/651 modules 30 active ...atabase\firebase_object_obser
 67% building modules 621/652 modules 31 active ...larfire2\database\query_obser
 67% building modules 622/652 modules 30 active ...larfire2\database\query_obser
 67% building modules 623/652 modules 29 active ...larfire2\database\query_obser
 67% building modules 624/652 modules 28 active ...larfire2\database\query_obser
 67% building modules 625/652 modules 27 active ...larfire2\database\query_obser
 67% building modules 626/652 modules 26 active ...larfire2\database\query_obser
 67% building modules 627/652 modules 25 active ...larfire2\database\query_obser
 67% building modules 628/652 modules 24 active ...larfire2\database\query_obser
 67% building modules 629/652 modules 23 active ...larfire2\database\query_obser
 67% building modules 630/652 modules 22 active ...larfire2\database\query_obser
 68% building modules 631/652 modules 21 active ...larfire2\database\query_obser
 68% building modules 632/652 modules 20 active ...larfire2\database\query_obser
 68% building modules 632/653 modules 21 active ...ler\src\output\abstract_js_em
 67% building modules 632/654 modules 22 active ...compiler\src\i18n\extractor_m
 67% building modules 632/655 modules 23 active ...mpiler\src\i18n\translation_b
 67% building modules 632/656 modules 24 active ...gular\compiler\src\ml_parser\
 67% building modules 632/657 modules 25 active ...\@angular\compiler\src\i18n\d
 67% building modules 632/658 modules 26 active ...r\src\view_compiler\compile_m
 67% building modules 632/659 modules 27 active ...er\src\view_compiler\compile_
 67% building modules 632/660 modules 28 active ...mpiler\src\view_compiler\cons
 67% building modules 632/661 modules 29 active ...ar\compiler\src\view_compiler
 67% building modules 632/662 modules 30 active ...ler\src\view_compiler\compile
 67% building modules 632/663 modules 31 active ...ler\src\view_compiler\event_b
 67% building modules 632/664 modules 32 active ...src\view_compiler\lifecycle_b
 67% building modules 632/665 modules 33 active ...\src\view_compiler\property_b
 67% building modules 633/665 modules 32 active ...\src\view_compiler\property_b
 67% building modules 634/665 modules 31 active ...\src\view_compiler\property_b
 67% building modules 634/666 modules 32 active ...modules\rxjs\scheduler\AsyncA
 67% building modules 634/667 modules 33 active ...ules\rxjs\scheduler\AsyncSche
 66% building modules 634/668 modules 34 active ...ar2-firebase\node_modules\ms\
 66% building modules 634/669 modules 35 active ...\compiler\src\ml_parser\xml_p
 66% building modules 634/670 modules 36 active ...gular\compiler\src\i18n\parse
 66% building modules 634/671 modules 37 active ...er\src\i18n\serializers\seria
 66% building modules 634/672 modules 38 active ...er\src\i18n\serializers\xml_h
 66% building modules 635/672 modules 37 active ...er\src\i18n\serializers\xml_h
 66% building modules 636/672 modules 36 active ...er\src\i18n\serializers\xml_h
 66% building modules 637/672 modules 35 active ...er\src\i18n\serializers\xml_h
 66% building modules 638/672 modules 34 active ...er\src\i18n\serializers\xml_h
 67% building modules 639/672 modules 33 active ...er\src\i18n\serializers\xml_h
 67% building modules 640/672 modules 32 active ...er\src\i18n\serializers\xml_h
 67% building modules 641/672 modules 31 active ...er\src\i18n\serializers\xml_h
 67% building modules 642/672 modules 30 active ...er\src\i18n\serializers\xml_h
 67% building modules 643/672 modules 29 active ...er\src\i18n\serializers\xml_h
 67% building modules 644/672 modules 28 active ...er\src\i18n\serializers\xml_h
 67% building modules 645/672 modules 27 active ...er\src\i18n\serializers\xml_h
 67% building modules 646/672 modules 26 active ...er\src\i18n\serializers\xml_h
 67% building modules 647/672 modules 25 active ...er\src\i18n\serializers\xml_h
 67% building modules 648/672 modules 24 active ...er\src\i18n\serializers\xml_h
 67% building modules 649/672 modules 23 active ...er\src\i18n\serializers\xml_h
 68% building modules 650/672 modules 22 active ...er\src\i18n\serializers\xml_h
 68% building modules 651/672 modules 21 active ...er\src\i18n\serializers\xml_h
 68% building modules 652/672 modules 20 active ...er\src\i18n\serializers\xml_h
 68% building modules 653/672 modules 19 active ...er\src\i18n\serializers\xml_h
 68% building modules 654/672 modules 18 active ...er\src\i18n\serializers\xml_h
 68% building modules 655/672 modules 17 active ...er\src\i18n\serializers\xml_h
 68% building modules 656/672 modules 16 active ...er\src\i18n\serializers\xml_h
 68% building modules 657/672 modules 15 active ...er\src\i18n\serializers\xml_h
 68% building modules 658/672 modules 14 active ...er\src\i18n\serializers\xml_h
 68% building modules 659/672 modules 13 active ...er\src\i18n\serializers\xml_h
 68% building modules 660/672 modules 12 active ...er\src\i18n\serializers\xml_h
 69% building modules 661/672 modules 11 active ...er\src\i18n\serializers\xml_h
 68% building modules 661/673 modules 12 active ...re2\node_modules\firebase\fir
 68% building modules 661/674 modules 13 active ...de_modules\angularfire2\inter
 68% building modules 662/674 modules 12 active ...de_modules\angularfire2\inter
 69% building modules 663/674 modules 11 active ...de_modules\angularfire2\inter
 69% building modules 664/674 modules 10 active ...de_modules\angularfire2\inter
 69% building modules 665/674 modules 9 active ...de_modules\angularfire2\interf
 69% building modules 666/674 modules 8 active ...de_modules\angularfire2\interf
 69% building modules 666/675 modules 9 active ...odules\rxjs\operator\combineLa
 69% building modules 666/676 modules 10 active ...angular\compiler\src\i18n\i18
 69% building modules 666/677 modules 11 active ...ular\compiler\src\i18n\i18n_p
 68% building modules 666/678 modules 12 active ...node_modules\rxjs\scheduler\A
 68% building modules 666/679 modules 13 active ...rebase\node_modules\rxjs\Sche
 68% building modules 666/680 modules 14 active ...ar\compiler\src\ml_parser\xml
 68% building modules 667/680 modules 13 active ...ar\compiler\src\ml_parser\xml
 68% building modules 668/680 modules 12 active ...ar\compiler\src\ml_parser\xml
 69% building modules 669/680 modules 11 active ...ar\compiler\src\ml_parser\xml
 69% building modules 670/680 modules 10 active ...ar\compiler\src\ml_parser\xml
 69% building modules 671/680 modules 9 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 672/680 modules 8 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 673/680 modules 7 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 674/680 modules 6 active ...e\src\tasks\components\task-li
 69% building modules 674/681 modules 7 active ...r\src\i18n\serializers\placeho
 69% building modules 675/681 modules 6 active ...e\src\tasks\components\task-li
 69% building modules 676/681 modules 5 active ...e\src\tasks\components\task-li
 69% building modules 677/681 modules 4 active ...e\src\tasks\components\task-li
 69% building modules 678/681 modules 3 active ...e\src\tasks\components\task-li
 69% building modules 679/681 modules 2 active ...e\src\tasks\components\task-li
 69% building modules 680/681 modules 1 active ...e\src\tasks\components\task-li
 69% building modules 680/682 modules 2 active ...de_modules\css-loader\lib\css-
 69% building modules 681/682 modules 1 active ...e\src\tasks\components\task-li
Time: 11899ms
                       Asset       Size  Chunks             Chunk Names
        apple-touch-icon.png    2.77 kB          [emitted]
                   vendor.js    2.52 MB       0  [emitted]  vendor
                polyfills.js     428 kB       2  [emitted]  polyfills
               vendor.js.map    2.38 MB       0  [emitted]  vendor
                 main.js.map     439 kB       1  [emitted]  main
            polyfills.js.map     521 kB       2  [emitted]  polyfills
apple-touch-icon-114x114.png    1.79 kB          [emitted]
apple-touch-icon-144x144.png    2.76 kB          [emitted]
  android-chrome-192x192.png      14 kB          [emitted]
  apple-touch-icon-57x57.png    1.02 kB          [emitted]
  apple-touch-icon-72x72.png    1.19 kB          [emitted]
           browserconfig.xml  387 bytes          [emitted]
                     main.js     441 kB       1  [emitted]  main
           favicon-16x16.png  812 bytes          [emitted]
                 favicon.ico    15.1 kB          [emitted]
               manifest.json  198 bytes          [emitted]
           favicon-32x32.png    1.36 kB          [emitted]
          mstile-144x144.png    5.07 kB          [emitted]
          mstile-150x150.png    5.05 kB          [emitted]
          mstile-310x150.png    5.35 kB          [emitted]
          mstile-310x310.png    20.1 kB          [emitted]
            mstile-70x70.png     3.4 kB          [emitted]
       safari-pinned-tab.svg    2.53 kB          [emitted]
                  index.html     1.8 kB          [emitted]
chunk    {0} vendor.js, vendor.js.map (vendor) 1.98 MB {2} [initial] [rendered]
chunk    {1} main.js, main.js.map (main) 409 kB {0} [initial] [rendered]
chunk    {2} polyfills.js, polyfills.js.map (polyfills) 396 kB [entry] [rendered
]

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.promise.d.ts
(26,14): error TS2687: All declarations of 'prototype' must have identical modif
iers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.iterable.d.ts
(33,5): error TS2687: All declarations of 'value' must have identical modifiers.


ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.collection.d.ts
(28,14): error TS2687: All declarations of 'size' must have identical modifiers.


ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.collection.d.ts
(34,14): error TS2687: All declarations of 'prototype' must have identical modif
iers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.collection.d.ts
(55,14): error TS2687: All declarations of 'prototype' must have identical modif
iers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.collection.d.ts
(65,14): error TS2687: All declarations of 'size' must have identical modifiers.


ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.collection.d.ts
(71,14): error TS2687: All declarations of 'prototype' must have identical modif
iers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.collection.d.ts
(90,14): error TS2687: All declarations of 'prototype' must have identical modif
iers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.core.d.ts
(21,14): error TS2300: Duplicate identifier 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.core.d.ts
(220,14): error TS2687: All declarations of 'EPSILON' must have identical modifi
ers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.core.d.ts
(255,14): error TS2687: All declarations of 'MAX_SAFE_INTEGER' must have identic
al modifiers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.core.d.ts
(262,14): error TS2687: All declarations of 'MIN_SAFE_INTEGER' must have identic
al modifiers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\node_modules\typescript\
lib\lib.es2015.core.d.ts
(407,14): error TS2687: All declarations of 'flags' must have identical modifier
s.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(3,14): error TS2300: Duplicate identifier 'PropertyKey'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(7,5): error TS2687: All declarations of 'value' must have identical modifiers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(245,5): error TS2687: All declarations of 'EPSILON' must have identical modifie
rs.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(280,5): error TS2687: All declarations of 'MAX_SAFE_INTEGER' must have identica
l modifiers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(287,5): error TS2687: All declarations of 'MIN_SAFE_INTEGER' must have identica
l modifiers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(343,5): error TS2687: All declarations of 'flags' must have identical modifiers
.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(495,5): error TS2687: All declarations of 'prototype' must have identical modif
iers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(558,5): error TS2687: All declarations of 'size' must have identical modifiers.


ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(567,5): error TS2687: All declarations of 'prototype' must have identical modif
iers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(578,5): error TS2687: All declarations of 'size' must have identical modifiers.


ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(588,5): error TS2687: All declarations of 'prototype' must have identical modif
iers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(593,11): error TS2428: All declarations of 'WeakMap' must have identical type p
arameters.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(601,27): error TS2344: Type 'K' does not satisfy the constraint 'object'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(602,57): error TS2344: Type 'K' does not satisfy the constraint 'object'.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(603,5): error TS2687: All declarations of 'prototype' must have identical modif
iers.

ERROR in C:\Users\Me\Development\todo-angular2-firebase\typings\globals\es6-shim
\index.d.ts
(617,5): error TS2687: All declarations of 'prototype' must have identical modif
iers.
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  4.39 kB       0
    chunk    {0} index.html 1.8 kB [entry] [rendered]
webpack: Failed to compile.
`

**Comment by r-park** [comment]
Looks like you've installed es6-shim typings, which are probably conflicting with the core-js typings.

Try cloning the repo into a new/clean directory and run `npm install` and `npm start`.

**Comment by joshdobbs** [comment]
d'oh! Thanks!
