### ISSUE TITLE
Angular4

### ISSUE THREAD

**Issue by rmckeel** [r-park/todo-angular2-firebase#133]
Love the NG2 TODO example - thanks for writing it!

I have a feature request for an Angular4 app.  [angularfire2](https://github.com/angular/angularfire2/blob/master/docs/version-4-upgrade.md) made several breaking changes in the codebase, and the 4.0.0 is currently at stage rc0.  Would be nice to see if/how this same thing can be done on NG4  (I say if since it seems many of the NG4 packages are still beta / rc and may not be feature complete).

**Comment by r-park** [comment]
Thanks for the nudge @rmckeel :)

**Comment by rmckeel** [comment]
You bet! Looking forward to seeing the update! 👍
