### ISSUE TITLE
Convert to CLI

### ISSUE THREAD

**Issue by lebsral** [r-park/todo-angular2-firebase#136]
I created a fork 
https://github.com/lebsral/todo-angular2-firebase
that uses the Angular CLI instead.

I hope this is helpful to those who want to see the Firebase/Angular/RXJS magic with less Webpack tooling cluttering things up.

Suggestions welcome.

Should this live as a separate fork?  Or do you want to eventually merge it back into here?

**Comment by lebsral** [comment]
Also,  some of the tests seem to be centered around "the server."  Those tests don't make sense in the cli world, right?

**Comment by r-park** [comment]
Hi @lebsral 

Thanks very much — that's great 👍 
Please feel free to open a PR (from your feature branch `feature/convertToCLI `).
