### ISSUE TITLE
Security json file not included in configuration

### ISSUE THREAD

**Issue by LukeSchlangen** [r-park/todo-angular2-firebase#38]
It might be good to include the security file in the configuration for login so that people forking this repo have an example of how to do that. Do you have firebase security rules written for this app that could be included in this project?

https://www.firebase.com/docs/security/guide/user-security.html

That way when someone forks this repo they won't need to rewrite all of the security rules.

(This is an amazing repo, it's one of the only angular 2 + firebase repos I can find that's still working, so thank you so much for creating it.)

**Comment by r-park** [comment]
Thanks for the suggestion @LukeSchlangen 

Resolved by https://github.com/r-park/todo-angular2-firebase/commit/281b0bfa73b9662121307ab9a9a4091daca5afd8
