### ISSUE TITLE
explain  new ReplaySubject(1);

### ISSUE THREAD

**Issue by bradintheusa** [r-park/todo-angular2-firebase#39]
This is a great example but can someone point me to a link that explains how these lines work

Thanks, much appreciated.

  ```
task-store.ts

tasks: ReplaySubject<List<any>> = new ReplaySubject(1);


  subscribe(next: (list: List<any>) => void): any {
    return this.tasks.subscribe(next);
  }
```

**Comment by r-park** [comment]
The [ReplaySubject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/replaysubject.md) is used to stream the list of tasks to the `TaskList` component. The component uses the angular2 `async` pipe to automatically subscribe to the ReplaySubject, and renders the list when the ReplaySubject emits a new/updated list of tasks.
```
<task-item [model]="task" *ngFor="#task of tasks | async | filterTasks:filter"></task-item>
```

**Comment by r-park** [comment]
The `subscribe()` function is no longer used and has been removed https://github.com/r-park/todo-angular2-firebase/commit/1225761bed201392e5e8c35ff1667de4ad80adf6
```
subscribe(next: (list: List<any>) => void): any {
  return this.tasks.subscribe(next);
}
```

**Comment by bradintheusa** [comment]
Thanks.  Much appreciated.
