### ISSUE TITLE
auth-route-helper constructor not called

### ISSUE THREAD

**Issue by doovers** [r-park/todo-angular2-firebase#42]
I'm trying to implement the AuthRouteHelper class in my app but I'm having a problem with the `requireUnauth` and `requireAuth` static functions. They are not calling the `AuthRouteHelper` constructor on the line `const { auth, router } = AuthRouteHelper;` so the next line is throwing 

> TypeError: undefined is not an object (evaluating 'auth.authenticated')

Any ideas what's going on here? Note: the class code is currently identical to yours.

**Comment by r-park** [comment]
Are you injecting the AuthRouteHelper into your [root component](https://github.com/r-park/todo-angular2-firebase/blob/master/src/components/app/app.ts#L29)?

**Comment by doovers** [comment]
No I wasn't and that seems to have fixed it thank you. By the way, I think this is one of the best angular2 resources available. Thank you for your excellent work!

**Comment by r-park** [comment]
:+1:
