### ISSUE TITLE
getting error when i run gulp

### ISSUE THREAD

**Issue by rahulbats** [r-park/todo-angular2-firebase#43]
Hi,
i followed the steps after checking out the code 
when i run gulp as mentioned in README 
./node_modules/.bin/gulp
i get this error

ERROR in ./src/main.ts
Module build failed: A file specified in tsconfig.json could not be found: /Users/z001mss/todo-angular2-firebase/typings/browser.d.ts

**Comment by r-park** [comment]
Hi @rahulbats — the `npm install` command should have installed typings. If `typings/browser.d.ts` doesn't exist, you can try running `npm install` again.

**Comment by raphaelcunha** [comment]
I have the same problem was not found file browser.d.ts, NPM install before and after the problem continues

**Comment by r-park** [comment]
@raphaelcunha try `npm run typings`

Also, which version of node and npm are you running?

**Comment by raphaelcunha** [comment]
@r-park 

I run the command and everything worked as expected, thank you.
npm -v  3.6.0
node -v 5.7.1
