### ISSUE TITLE
Any progress on `CanActivate` ?

### ISSUE THREAD

**Issue by gigocabrera** [r-park/todo-angular2-firebase#47]
In your [auth-route-helper.ts](https://github.com/r-park/todo-angular2-firebase/blob/master/src/core/auth/auth-route-helper.ts) file you wrote: 

* This is an ugly workaround until `CanActivate` supports DI

Any progress that you know of? 

Sorry if the question sounds stupid but I'm new with this technology and I'm looking for a working example on this feature so I can understand it better. Thanks!

**Comment by r-park** [comment]
As far as I know it's still being worked on — looks like it's scheduled for the [Release Candidate](https://github.com/angular/angular/milestones).

**Comment by gigocabrera** [comment]
Awesome thanks for the update. I'll keep monitoring your project in hopes that you update it !!!
