### ISSUE TITLE
Firebase 3.0

### ISSUE THREAD

**Issue by wangbourne** [r-park/todo-angular2-firebase#58]
any plan to support Firebase 3.0, which was introduce Google IO 2016?

**Comment by r-park** [comment]
Waiting for [angularfire2 to support Firebase 3.0 SDK](https://github.com/angular/angularfire2/pull/200)

**Comment by liangwang320** [comment]
Firebase3.0 is ready to use :)

**Comment by r-park** [comment]
Master branch has been updated with support for:
- Angular2 `2.0.0-rc.3`
- Angular2 Router `3.0.0-alpha.8`
- AngularFire2 `2.0.0-beta.2`
- Firebase `SDK 3 `
