### ISSUE TITLE
Why window.location.replace('/') after signOut? canActivate doesn't cover that?

### ISSUE THREAD

**Issue by bogacg** [r-park/todo-angular2-firebase#79]
Nice example code, thanks. I've noticed something though while going over your code:
After auth.signOut, window.location.replace('/') gets called. 

I've changed my authentication to be similar to this example, in a service, and without using window.location.replace, page stays in signed out route.

I don't get it, canActivate code already checks if authentication state is valid or not, if not it redirects to root route, but doesn't get called. Why?

**Comment by r-park** [comment]
Hi @bogacg — `window.location.replace` isn't required. I think that was a hold-over from a much earlier version when angular was in alpha.
