### ISSUE TITLE
zone.js:461  Unhandled Promise rejection: Template parse errors:

### ISSUE THREAD

**Issue by sebfag** [r-park/todo-angular2-firebase#81]
Hi, 

just saw that you have updated your project to RC5, thanks. There are some errors when  serving the project in production mode.

npm run start -> fine
npm run build -> fine 
npm run server (or firebase serve) leads to the following error : 

zone.js:461 Unhandled Promise rejection: Template parse errors:
Can't bind to 'task' since it isn't a known property of 'task-item'.
1. If 'task-item' is an Angular component and it has 'task' input, then verify that it is part of this module.
2. If 'task-item' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
      <task-item
        *ngFor="let task of tasks | async"
        [ERROR ->][task]="task"
        (remove)="remove.emit(task)"
        (update)="update.emit({task: task, changes"): t@10:8 ; Zone: <root> ; Task: Promise.then ; Value:

**Comment by r-park** [comment]
Hi @sebfag — thanks very much for reporting this. Seems to be related to https://github.com/angular/angular/issues/10618#issuecomment-239497694.
