### ISSUE TITLE
Mark all completed

### ISSUE THREAD

**Issue by bradintheusa** [r-park/todo-angular2-firebase#85]
Hi

This is a great example I have learned a lot from it.   What would be the best way to implement a mark all completed featured.

Thanks

**Comment by strike-sbolel** [comment]
What do you think @r-park? I can try to take a stab at this.

**Comment by r-park** [comment]
If you need to work with the entities returned by firebase list/observable, it can be advantageous to cache the entities locally. Depending on your needs, you can use a simple array, [an observable](https://github.com/r-park/todo-angular2-firebase/blob/dev-mark-all/src/tasks/services/task-service.ts#L13), or something more robust like [@ngrx/store](https://github.com/ngrx/store).

Take a look at commit https://github.com/r-park/todo-angular2-firebase/commit/0ad1da1d1670e0a35e1a9c8e3eb8252797da771e from [this branch](https://github.com/r-park/todo-angular2-firebase/tree/dev-mark-all) for an example using a `BehaviorSubject` to store tasks locally.
