### ISSUE TITLE
question: lock node engine to >= v6.x?

### ISSUE THREAD

**Issue by sbolel** [r-park/todo-angular2-firebase#97]
I see that CircleCI uses node `6.4`, and package.json engine is `>=5.11`.

How do you feel about locking the node engine to >= `6.4.0` in package.json and .circle.yml?

We recently switched to `6.5.0` at my work and haven't had any issues.

**Comment by sbolel** [comment]
Sweet! I'll create a PR. `6.4` or `6.5`?

**Comment by r-park** [comment]
6.5 please

**Comment by sbolel** [comment]
PR #98 submitted :)
